config/routes.rb
Rails.application.routes.draw do
  resources :post_types
  devise_for :users
  resources :posts
  get 'about', to: 'about#index'
  root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  require 'carrierwave/orm/activerecord'
  belongs_to :user
  belongs_to :post_type, optional: true

  mount_uploaders :images, ImageUploader
  #serialize :images, JSON
end

app/models/post_type.rb
class PostType < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	render "front/about"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_constants

  def set_constants
    @post_types2 = PostType.all
    @posts2 = Post.all
  end
end

app/controllers/post_types_controller.rb
class PostTypesController < ApplicationController
  before_action :set_post_type, only: [:show, :edit, :update, :destroy]

  # GET /post_types
  # GET /post_types.json
  def index
    @post_types = PostType.all
  end

  # GET /post_types/1
  # GET /post_types/1.json
  def show
  end

  # GET /post_types/new
  def new
    @post_type = PostType.new
  end

  # GET /post_types/1/edit
  def edit
  end

  # POST /post_types
  # POST /post_types.json
  def create
    @post_type = PostType.new(post_type_params)

    respond_to do |format|
      if @post_type.save
        format.html { redirect_to @post_type, notice: 'Post type was successfully created.' }
        format.json { render :show, status: :created, location: @post_type }
      else
        format.html { render :new }
        format.json { render json: @post_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_types/1
  # PATCH/PUT /post_types/1.json
  def update
    respond_to do |format|
      if @post_type.update(post_type_params)
        format.html { redirect_to @post_type, notice: 'Post type was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_type }
      else
        format.html { render :edit }
        format.json { render json: @post_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_types/1
  # DELETE /post_types/1.json
  def destroy
    @post_type.destroy
    respond_to do |format|
      format.html { redirect_to post_types_url, notice: 'Post type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_type
      @post_type = PostType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_type_params
      params.require(:post_type).permit(:title)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    if params[:post_type_id]
      @posts = Post.all.where(post_type_id: params[:post_type_id])
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.all
    @texts = @post.text.split('@')
    (@texts += ['']) if @post.text.last == '@'
  end

  # GET /posts/new
  def new
    @post_types = PostType.all
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post_types = PostType.all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params2 = params.require(:post).permit(:title, :post_type_id, :text, {images: []})
      params2[:user_id] =  current_user.id
      params2
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_types_helper.rb
module PostTypesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/front/_header.html.erb
<%= render 'front/devise_tools' %>


<header id="header">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="header_top">
        <div class="header_top_left">
          <ul class="top_nav">
            <li> <%= link_to 'home', root_path %> </li>
            <li><a href="/about">About</a></li>
            <li><a href="http://asoiu.com/">ASOIU</a></li>
            <li>
            <% if current_user %>
              <%= link_to "log out", destroy_user_session_path, method: 'delete' %>
            <% else %>
              <%= link_to "log in", new_user_session_path %>
            <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>



<div class="col-lg-12 col-md-12 col-sm-12">
  <div class="header_bottom">
    <div class="logo_area"><a href="#" class="logo"><img src="/images/logo.jpg" alt=""></a></div>
  </div>
</div>
</div>
</header>
<section id="navArea">
  <nav class="navbar navbar-inverse" role="navigation">

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav main_nav">
        <% @post_types2.each do |type| %>
          <li> <%= link_to type.title, posts_path(post_type_id: type.id) %> </li>
        <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to 'New Post', new_post_path %> </li>
      </ul>
    </div>
  </nav>

</section>

app/views/front/_other_stuff.html.erb
<div class="container">
      <div class="rightblock">
<script type="text/javascript">

document.write(VK.Share.button()); 
</script>

<br>

<script type="text/javascript">
document.write("<a href='//www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t17.6;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";h"+escape(document.title.substring(0,150))+";"+Math.random()+
"' alt='' title='LiveInternet: показано число просмотров за 24"+
" часа, посетителей за 24 часа и за сегодня' "+
"border='0' width='88' height='31'><\/a>")
</script>

</div>
</div>

app/views/front/_side.html.erb
<div class="col-lg-4 col-md-4 col-sm-4">
  <div class="latest_post">
    <h2><span>All postes</span></h2>
    <div class="latest_post_container">
      <ul class="latest_postnav">
        <% @posts2.each do |post| %>
        <li>
          <div class="media"> <%= link_to image_tag(post.images[0].url), post, class: "media-left" %>
            <div class="media-body"> <%= link_to post.title, post, class: 'catg_title' %> </div>
          </div>
        </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/front/about.html.erb
 <section id="contentSection">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="left_content">
          <div class="single_page">
            <ol class="breadcrumb">
            </ol>
                        <h1>About us</h1>

            <div class="single_page_content">
            <p> Author of this site - Evgeny Vorobyev.</p>
            <a href="https://vk.com/onizik55rus"> Vk.com profile</a>
            <p> Student of PIN-151 group.</p>
            </div>
            </div>
</div>
</div>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheCoolestGameBlog</title>
    <meta name="google-site-verification" content="GB5AEQjHL-6lcIH6KO7cMtUTpt6HL5vL5Candv4dYh4" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>

    <%= render 'front/header' %>

<script type="text/javascript" src="https://vk.com/js/api/share.js?93" charset="windows-1251"></script>
  </head>

  <body>
    <%= yield %>
    <%= render 'front/other_stuff'%>
  </body>
</html>

app/views/post_types/_form.html.erb
<%= form_with(model: post_type, local: true) do |form| %>
  <% if post_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_type.errors.count, "error") %> prohibited this post_type from being saved:</h2>

      <ul>
      <% post_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_types/edit.html.erb
<h1>Editing Post Type</h1>

<%= render 'form', post_type: @post_type %>

<%= link_to 'Show', @post_type %> |
<%= link_to 'Back', post_types_path %>

app/views/post_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Types</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_types.each do |post_type| %>
      <tr>
        <td><%= post_type.title %></td>
        <td><%= link_to 'Show', post_type %></td>
        <td><%= link_to 'Edit', edit_post_type_path(post_type) %></td>
        <td><%= link_to 'Destroy', post_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Type', new_post_type_path %>

app/views/post_types/new.html.erb
<h1>New Post Type</h1>

<%= render 'form', post_type: @post_type %>

<%= link_to 'Back', post_types_path %>

app/views/post_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post_type.title %>
</p>

<%= link_to 'Edit', edit_post_type_path(@post_type) %> |
<%= link_to 'Back', post_types_path %>

app/views/posts/_form.html.erb
  <%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.file_field :images, multiple: true %>
  </div>

    <div class="form-group">
      <%= form.label :type %>
      <%= form.select :post_type_id, post_types.collect{|type| [type.title, type.id]},
                   {include_blank: "without type"}, class: 'form-control' %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
	<h1>Editing Post</h1>

<%= render 'form', post: @post, post_types: @post_types %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="col-lg-8 col-md-8 col-sm-8">
  <% @posts.each do |post| %>
  <div class="single_iteam"> <%= link_to image_tag(post.images[0].url), post %>
    <div class="slider_article">
      <h2> <%= link_to post.title, class: 'slider_tittle' %> </h2>
      <p> <%= post.text.tr('@', '')[0..100] %> </p>
    </div>
  </div>
  <% end %>

</div>

<%= render 'front/side', posts: @posts %>

app/views/posts/new.html.erb
	<h1>New Post</h1>

<%= render 'form', post: @post, post_types: @post_types %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<section id="contentSection">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8">
      <% if current_user %>
        <%= link_to 'edit', edit_post_path(@post), class: 'btn btn-dark' %>
        <%= link_to 'delete', post_path(@post), method: 'delete', class: 'btn btn-dark' %>
      <% end %>
      <div class="left_content">
        <div class="single_page">
          <ol class="breadcrumb">
          </ol>
          <h1> <%= @post.title %></h1>
          <div class="single_page_content">
            <%= image_tag @post.images[0].url %>
            <br><br>
            <% @texts.each_index do |index| %>
              <p> <%= @texts[index] %> </p>
              <%= image_tag(@post.images[index + 1]&.url) if index < @post.images.length - 1 %>
              <br>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'front/side', posts: @posts %>
  </div>
</section>